spring.application.name=SpringEcom2
server.port = 8081

spring.datasource.url=jdbc:postgresql://localhost:5432/projects1
spring.datasource.username=postgres
spring.datasource.password=xxxxxxx
spring.datasource.driver-class-name=org.postgresql.Driver

! Note : Run the query in "insert - data" file in database itself to get the values in the table

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#when we are using Large Object it sometimes gives auto commit error, to avoid use below
spring.datasource.hikari.auto-commit = false

